const JobActionTypes = {
    JOB_FETCH_START: 'JOB_FETCH_START',
    JOB_FETCH_SUCCESS: 'JOB_FETCH_SUCCESS',
    JOB_FETCH_FAILURE: 'JOB_FETCH_FAILURE',
    JOB_CREATE_START: 'JOB_CREATE_START',
    JOB_CREATE_SUCCESS: 'JOB_CREATE_SUCCESS',
    JOB_CREATE_FAILURE: 'JOB_CREATE_FAILURE',
    JOB_DELETE_START: 'JOB_DELETE_START',
    JOB_DELETE_SUCCESS: 'JOB_DELETE_SUCCESS',
    JOB_DELETE_FAILURE: 'JOB_DELETE_FAILURE'
};

export default JobActionTypes;