const UserActionTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    AUTHENTICATION_TOKEN_START: 'AUTHENTICATION_TOKEN_START',
    AUTHENTICATION_TOKEN_SUCCESS: 'AUTHENTICATION_TOKEN_SUCCESS',
    AUTHENTICATION_TOKEN_FAILURE: 'AUTHENTICATION_TOKEN_FAILURE'
};

export default UserActionTypes;